kubernetesClusterDomain: cluster.local
tbot:
  replicas: 1
  serviceAccount:
    annotations: {}
  tbot:
    args:
    - start
    - -c
    - /config/tbot.yaml
    env:
      kubernetesTokenPath: /var/run/secrets/tokens/join-sa-token
      teleportAnonymousTelemetry: "1"
    image:
      repository: public.ecr.aws/gravitational/teleport-distroless
      tag: 15.0.1
tbotConfig:
  tbotYaml: |-
    version: v2
    onboarding:
      join_method: kubernetes
      # ensure token is set to the name of the join token you created earlier
      token: bot-kubernetes
    storage:
      # a memory destination is used for the bots own state since the kubernetes
      # join method does not require persistence.
      type: memory
    # ensure this is configured to the address of your Teleport Proxy or
    # Auth Server. Prefer the address of the Teleport Proxy.
    auth_server: example.teleport.sh:443
    # outputs will be filled in during the completion of an access guide.
    outputs: []
